### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by raijinspecial** [danmcduff/scampsdataset#1]
Hi, thanks for releasing this fascinating dataset.

I am having issues downloading the complete 600GB file, it has failed multiple times now around 89% complete with this

2022-06-16 15:58:57 (14.3 MB/s) - Read error at byte 530969526272/593450450686 (Connection reset by peer). Retrying.

Do you have an alternate link to download from or recommendation on how to download? It has failed with both using wget and downloading with a browser.

Thanks!

**Comment by danmcduff** [comment]
Thanks for the message @raijinspecial - I am looking into this to see if the file is somehow corrupted or if you just need a fault tolerance download method and will get back to you.

**Comment by raijinspecial** [comment]
Thanks for looking into it. 

I have been able to successfully download the complete set with both curl and wget. Perhaps it was just overwhelmed by traffic just after your initial release?

Please feel free to close this when you are finished looking into it. 
cheers

**Comment by danmcduff** [comment]
Thanks for the confirmation.  I'll close this issue as the file size looks correct.
