### ISSUE TITLE
Divison of the Main SCAMPS dataset

### ISSUE THREAD

**Issue by Taimoor-R** [danmcduff/scampsdataset#5]
Can you please provide smaller chucks of the dataset to download for convenience of individual/student researchers not having a lot of computational capabilities.

**Comment by ahn19** [comment]
For resume download, the author wrote python code.
https://github.com/spaceromany/resume_download_for_scamps

**Comment by Taimoor-R** [comment]
Thank you, this will hopefully solve the problem.
